name: Fintech Analytics CI Pipeline

on:
  push:
    branches: [ "main", "task-*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Check out code
    - uses: actions/checkout@v3

    # 2. Setup Python
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    # 3. Cache pip (massive speed improvement)
    - name: Cache pip packages
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

    # 4. Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --default-timeout=100 --retries=10 -r requirements.txt

    # 5. Linting
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    # 6. Tests
    - name: Run Unit Tests
      run: |
        pytest || (if [ $? -eq 5 ]; then echo "No tests found â€” skipping."; exit 0; else exit 1; fi)
